site_name: mpvue-docs
site_url: http://mpvue.com/
site_description: 'mpvue-docs'
theme_dir: fedocs
site_favicon: 'assets/favicon.ico'
pages:
- [index.md, Home]
- [mpvue/index.md, Mpvue]
- [mpvue/mpvue-template-compiler.md, Mpvue]
- [mpvue/quickstart.md, Mpvue ]
- [mpvue/simple.md, Mpvue]
- [build/index.md, Build]
- [build/mpvue-loader.md, Build]
- [build/mpvue-webpack-target.md, Build ]
- [build/postcss-mpvue-wxss.md, Build]
- [build/px2rpx-loader.md, Build]
- [qa.md, Q&A]

extra:
  css: 'assets/style.css'